[package]
name          = "tellus-persistence-postgres"
description   = "PostgreSQL event and snapshot stores for tellus persistence"
version       = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
readme        = "README.md"
homepage      = { workspace = true }
repository    = { workspace = true }
documentation = "https://docs.rs/tellus-persistence-postgres/latest/tellus_persistence_postgres/"
publish       = true

[dependencies]
sqlx      = { workspace = true, features = [ "runtime-tokio", "tls-rustls-ring", "postgres", "migrate", "macros" ] }
thiserror = { workspace = true }
tellus    = { workspace = true, features = [ "persistence" ] }

[dev-dependencies]
anyhow                 = { workspace = true }
composed               = { workspace = true }
serde                  = { workspace = true, features = [ "derive" ] }
testcontainers-modules = { workspace = true, features = [ "postgres" ] }
tokio                  = { workspace = true, features = [ "macros", "rt-multi-thread" ] }
tracing-subscriber     = { workspace = true, features = [ "env-filter", "fmt", "json" ] }
tellus                 = { workspace = true, features = [ "persistence-tests" ] }
